pipeline {
  agent none
  parameters { string(name: 'ENV', defaultValue: 'dev', description: '') 
}
  stages {
    stage('Nginx Image') {
      agent {
        docker {
          image 'nginx'
        }
      }
      steps {
        echo "${env.BUILD_ID}"
	echo "${params.ENV}"
        echo "$GIT_BRANCH"
      }
    }
    stage('Build Image') {
      agent any
      steps {
		def customImage = docker.build("my-image:${env.BUILD_ID}")
		customImage.inside {
        sh 'make test'
	    }

}
}
}
}
