pipeline {
  agent none
  parameters { string(name: 'ENV', defaultValue: 'dev', description: '') 
}
  stages {
    stage('Nginx Image') {
      agent {
        docker {
          image 'nginx'
        }
      }
      steps {
        echo "${env.BUILD_ID}"
	echo "${params.ENV}"
        echo "$GIT_BRANCH"
      }
    }
    stage('Build Image') {
      agent any
      steps {
      sh 'docker build -t kienapp:${env.BUILD_ID} $GIT_URL'
	    }
}
}
}
